"""IF PEEP 2003 GREIT parity regression gate.

The fixture is generated by the EIDORS/MATLAB replay used for Andy Adler's
2003 IF PEEP data example.  It is intentionally not checked into git because
the exported MAT file is large; when present locally, this test guards the
full PyEIDORS replay path against channel-order, RM algebra, and desired-image
drift.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from scipy.io import loadmat

from pyeidors.inverse.greit import (
    build_greit_desired_images,
    calc_greit_rm,
    optimize_greit_weight_eidors_nf,
)
from pyeidors.inverse.reconstruction_matrix import reconstruct_difference_batch


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FIXTURE = (
    REPO_ROOT / "results" / "andy_if_peep_2003" / "eidors_if_peep_2003_export.mat"
)
FIXTURE_ENV = "PYEIDORS_IF_PEEP_2003_EXPORT"

pytestmark = pytest.mark.slow


def _fixture_path() -> Path:
    return Path(os.environ.get(FIXTURE_ENV, str(DEFAULT_FIXTURE))).expanduser()


def _require_fixture() -> Path:
    path = _fixture_path()
    if not path.exists():
        pytest.skip(
            "requires EIDORS IF PEEP 2003 export MAT fixture; "
            f"set {FIXTURE_ENV} or generate {DEFAULT_FIXTURE}"
        )
    return path


def _load_payload() -> dict[str, Any]:
    return loadmat(_require_fixture(), squeeze_me=True, struct_as_record=False)


def test_if_peep_2003_greit_training_components_close_to_eidors() -> None:
    payload = _load_payload()
    train_vh = _as_vector(payload["train_vh"])
    train_vi = _as_2d(payload["train_vi"])
    eidors_y = _as_2d(payload["train_y"])
    eidors_d = _as_2d(payload["train_d"])
    eidors_pjt = _as_2d(payload["train_pjt"])
    eidors_m = _as_2d(payload["train_m"])
    eidors_rm = _as_2d(payload["train_rm"])
    weight = float(np.asarray(payload["eidors_greit_weight"]).reshape(-1)[0])

    py_y = train_vi - train_vh.reshape(-1, 1)
    assert _relative_l2(py_y, eidors_y) <= 1.0e-14
    assert _corr(py_y, eidors_y) >= 1.0 - 1.0e-14

    py_d = _build_if_peep_desired_d(payload)
    assert _relative_l2(py_d, eidors_d) < 2.0e-2
    assert _corr(py_d, eidors_d) > 0.999

    components = calc_greit_rm(py_y, eidors_d, weight=weight, noise_covar=1.0)
    assert _relative_l2(components.pjt, eidors_pjt) < 1.0e-12
    assert _relative_l2(components.m, eidors_m) < 1.0e-12
    assert _relative_l2(components.rm, eidors_rm) < 1.0e-8
    assert _corr(components.rm, eidors_rm) > 1.0 - 1.0e-12


def test_if_peep_2003_eidors_noise_figure_weight_search_matches_eidors() -> None:
    payload = _load_payload()
    eidors_y = _as_2d(payload["train_y"])
    eidors_d = _as_2d(payload["train_d"])
    train_vh = _as_vector(payload["train_vh"])
    nf_target_y = _as_vector(payload["nf_target_y"])
    rec_volume_weights = _as_vector(payload["rec_volume_weights"])
    eidors_weight = float(np.asarray(payload["eidors_greit_weight"]).reshape(-1)[0])

    result = optimize_greit_weight_eidors_nf(
        eidors_y,
        eidors_d,
        vh=train_vh,
        signal_y=nf_target_y,
        volume_weights=rec_volume_weights,
        target_noise_figure=1.0,
        noise_covar=1.0,
        bracket=(-2.0, 2.0),
        tolerance=2.0e-4,
        maxiter=128,
    )

    assert result.weight == pytest.approx(eidors_weight, rel=2.0e-3)
    assert result.achieved_metric == pytest.approx(1.0, abs=1.0e-2)
    assert result.metadata["algorithm"] == "eidors_greit_noise_figure_search"
    assert result.metadata["nf_formula"] == "eidors_calc_noise_figure_linear"


def test_if_peep_2003_all_1500_frames_replay_eidors_reconstruction() -> None:
    payload = _load_payload()
    dd = _as_2d(payload["dd"])
    eidors_elem = _as_2d(payload["eidors_elem_data"])
    eidors_rm = _as_2d(payload["raw_delta_operator"])
    train_pjt = _as_2d(payload["train_pjt"])
    train_m = _as_2d(payload["train_m"])

    frames = (dd - dd[:, [0]]).T
    py_elem = _apply_rm(eidors_rm, frames)
    assert py_elem.shape == eidors_elem.shape
    assert _relative_l2(py_elem, eidors_elem) < 1.0e-12
    assert _corr(py_elem, eidors_elem) > 1.0 - 1.0e-12

    rebuilt_rm = np.linalg.solve(train_m.T, train_pjt.T).T
    rebuilt_elem = _apply_rm(rebuilt_rm, frames)
    assert _relative_l2(rebuilt_rm, eidors_rm) < 1.0e-8
    assert _relative_l2(rebuilt_elem, eidors_elem) < 1.0e-8
    assert _corr(rebuilt_elem, eidors_elem) > 1.0 - 1.0e-12


def _apply_rm(rm: np.ndarray, frames: np.ndarray) -> np.ndarray:
    result = reconstruct_difference_batch(
        rm,
        frames,
        normalize=False,
        device="cpu",
        dtype="float64",
        return_metadata=True,
    )
    metadata = dict(result.metadata)
    assert metadata["online_hot_path"] == "rm_matmul"
    assert metadata["n_frames"] == 1500
    return np.asarray(result.values, dtype=np.float64).T


def _build_if_peep_desired_d(payload: dict[str, Any]) -> np.ndarray:
    eidors_d = _as_2d(payload["train_d"])
    rec_centers = _eidors_pixel_centers(_as_2d(payload["train_rec_centers"]), eidors_d)
    xyzr = _as_2d(payload["train_xyzr"])
    rec_scaled, xyz_scaled = _eidors_normalized_2d_desired_inputs(rec_centers, xyzr)
    desired = build_greit_desired_images(
        rec_scaled,
        xyz=xyz_scaled,
        radius=0.205,
        desired_solution_fn="gauss",
        desired_options={
            "desired_img_threshold": 1.0e-4,
            "desired_img_steepness": 10.0,
            "desired_img_gauss_order": 5,
        },
    )
    assert desired.metadata["desired_image_sampling"] == "gauss"
    return np.asarray(desired.values, dtype=np.float64)


def _eidors_pixel_centers(rec_centers: np.ndarray, eidors_d: np.ndarray) -> np.ndarray:
    n_pixels = eidors_d.shape[0]
    if rec_centers.shape[0] == n_pixels:
        return np.ascontiguousarray(rec_centers[:, :3], dtype=np.float64)
    if rec_centers.shape[0] == 2 * n_pixels:
        return np.ascontiguousarray(
            rec_centers[:, :3].reshape(n_pixels, 2, 3).mean(axis=1),
            dtype=np.float64,
        )
    raise ValueError(
        "Cannot map EIDORS reconstruction centres to GREIT image parameters: "
        f"{rec_centers.shape[0]} centres for {n_pixels} desired-image rows."
    )


def _eidors_normalized_2d_desired_inputs(
    rec_centers: np.ndarray,
    xyzr: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    rec = np.asarray(rec_centers, dtype=np.float64).copy()
    if rec.shape[1] == 2:
        rec = np.column_stack([rec, np.zeros(rec.shape[0], dtype=np.float64)])
    xyz = np.asarray(xyzr[:3, :], dtype=np.float64).copy()
    mesh_min = np.min(rec[:, :2], axis=0)
    mesh_max = np.max(rec[:, :2], axis=0)
    mesh_mid = 0.5 * (mesh_min + mesh_max)
    max_range = float(np.max(mesh_max - mesh_min))
    if max_range <= np.finfo(np.float64).eps:
        raise ValueError("Invalid reconstruction centres for desired-image scaling.")
    rec[:, :2] = 2.0 * (rec[:, :2] - mesh_mid.reshape(1, 2)) / max_range
    xyz[:2, :] = 2.0 * (xyz[:2, :] - mesh_mid.reshape(2, 1)) / max_range
    rec[:, 2] = 0.0
    xyz[2, :] = 0.0
    return np.ascontiguousarray(rec), np.ascontiguousarray(xyz)


def _as_2d(value: Any) -> np.ndarray:
    array = np.asarray(value, dtype=np.float64)
    if array.ndim != 2:
        raise ValueError(f"Expected 2D array, got {array.shape}.")
    if not np.isfinite(array).all():
        raise FloatingPointError("array contains non-finite values.")
    return np.ascontiguousarray(array, dtype=np.float64)


def _as_vector(value: Any) -> np.ndarray:
    array = np.asarray(value, dtype=np.float64).reshape(-1)
    if array.size == 0:
        raise ValueError("Expected non-empty vector.")
    if not np.isfinite(array).all():
        raise FloatingPointError("vector contains non-finite values.")
    return np.ascontiguousarray(array, dtype=np.float64)


def _relative_l2(a: np.ndarray, b: np.ndarray) -> float:
    denom = max(1.0, float(np.linalg.norm(b.ravel())))
    return float(np.linalg.norm((a - b).ravel()) / denom)


def _corr(a: np.ndarray, b: np.ndarray) -> float:
    x = np.asarray(a, dtype=np.float64).ravel()
    y = np.asarray(b, dtype=np.float64).ravel()
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if x.size < 2 or np.std(x) == 0 or np.std(y) == 0:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])
