"""PyEIDORS inverse problem solver module."""

from .solvers.gauss_newton import GaussNewtonReconstructor
from .solvers.matrix_free_gn import MatrixFreeGNStepResult, solve_matrix_free_gn_step
from .solvers.sparse_bayesian import SparseBayesianReconstructor, SparseBayesianConfig
from .contracts import SolverOutput
from .block_system import (
    BlockCoupling,
    JointInverseBlockMetadata,
    ParameterBlock,
    build_electrode_movement_jacobian,
    build_sigma_contact_block_metadata,
    make_block_diagonal_inverse_action,
    prior_movement,
    scale_contact_impedance_update,
)
from .dual_mesh import CellMesh, DualMesh, VoxelGrid, coarse2fine
from .dynamic import (
    SPATIOTEMPORAL_GN_SCHEMA,
    SpatiotemporalGNResult,
    solve_batch_spatiotemporal_gn,
    temporal_difference_operator,
)
from .greit import (
    GREIT3DDistribution,
    GREIT_METRIC_KEYS,
    GREITRM,
    GREITTrainingTargets,
    build_3d_greit_rm,
    build_greit3d_distribution,
    generate_spherical_targets,
    greit_metrics,
    load_greit_rm,
    migrate_greit_rm_to_hdf5,
    write_greit_metrics_artifact,
)
from .prior import (
    RtRPrior,
    as_rtr_prior,
    graph_curvature_prior,
    graph_difference_operator,
    graph_laplacian,
    graph_ltl,
    graph_ltl_prior,
    load_rtr_prior_artifact,
    TVIRLSResult,
    solve_tv_irls_batch,
    solve_tv_irls_frame,
    tv_irls_objective,
    tv_irls_prior_from_state,
    write_rtr_prior_artifact,
)
from .postprocess import (
    TemporalTVPipelineResult,
    TVRefinementResult,
    exponential_smooth_frames,
    moving_average_frames,
    postprocess_rm_frames,
    refine_tv_pdhg,
    total_variation_norm,
)
from .matrix_free import DualMeshJacobianOperator
from .reconstruction_matrix import (
    OneStepRMResult,
    RMArtifact,
    build_one_step_rm,
    load_rm_artifact,
    migrate_rm_artifact_to_hdf5,
    reconstruct_difference,
    reconstruct_difference_batch,
    reconstruct_temporal_difference_batch,
    rm_signature,
    rm_signature_payload,
    write_forward_rm_benchmark_artifact,
    write_rm_artifact,
)
from .workflows import (
    perform_absolute_reconstruction,
    perform_difference_reconstruction,
    perform_sparse_absolute_reconstruction,
    perform_sparse_difference_reconstruction,
    ReconstructionResult,
)

__all__ = [
    "GaussNewtonReconstructor",
    "MatrixFreeGNStepResult",
    "solve_matrix_free_gn_step",
    "SparseBayesianReconstructor",
    "SparseBayesianConfig",
    "SolverOutput",
    "BlockCoupling",
    "JointInverseBlockMetadata",
    "ParameterBlock",
    "build_electrode_movement_jacobian",
    "build_sigma_contact_block_metadata",
    "make_block_diagonal_inverse_action",
    "prior_movement",
    "scale_contact_impedance_update",
    "CellMesh",
    "DualMesh",
    "VoxelGrid",
    "coarse2fine",
    "SPATIOTEMPORAL_GN_SCHEMA",
    "SpatiotemporalGNResult",
    "solve_batch_spatiotemporal_gn",
    "temporal_difference_operator",
    "GREIT3DDistribution",
    "GREIT_METRIC_KEYS",
    "GREITRM",
    "GREITTrainingTargets",
    "build_3d_greit_rm",
    "build_greit3d_distribution",
    "generate_spherical_targets",
    "greit_metrics",
    "load_greit_rm",
    "migrate_greit_rm_to_hdf5",
    "write_greit_metrics_artifact",
    "RtRPrior",
    "TVIRLSResult",
    "as_rtr_prior",
    "graph_curvature_prior",
    "graph_difference_operator",
    "graph_laplacian",
    "graph_ltl",
    "graph_ltl_prior",
    "load_rtr_prior_artifact",
    "solve_tv_irls_batch",
    "solve_tv_irls_frame",
    "tv_irls_objective",
    "tv_irls_prior_from_state",
    "write_rtr_prior_artifact",
    "TemporalTVPipelineResult",
    "TVRefinementResult",
    "exponential_smooth_frames",
    "moving_average_frames",
    "postprocess_rm_frames",
    "refine_tv_pdhg",
    "total_variation_norm",
    "DualMeshJacobianOperator",
    "OneStepRMResult",
    "RMArtifact",
    "build_one_step_rm",
    "load_rm_artifact",
    "migrate_rm_artifact_to_hdf5",
    "reconstruct_difference",
    "reconstruct_difference_batch",
    "reconstruct_temporal_difference_batch",
    "rm_signature",
    "rm_signature_payload",
    "write_forward_rm_benchmark_artifact",
    "write_rm_artifact",
    "perform_absolute_reconstruction",
    "perform_difference_reconstruction",
    "perform_sparse_absolute_reconstruction",
    "perform_sparse_difference_reconstruction",
    "ReconstructionResult",
]
